"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.wrapBaseTemplate = wrapBaseTemplate;
/**
 * Wraps email content in a standard branded HTML skeleton.
 */
function wrapBaseTemplate(title, preheader, content) {
    return "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>${title}</title>\n  <style>\n    body {\n      margin: 0;\n      padding: 0;\n      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n      background-color: #0a0a0a;\n      color: #ffffff;\n      -webkit-font-smoothing: antialiased;\n    }\n    .wrapper {\n      width: 100%;\n      table-layout: fixed;\n      background-color: #0a0a0a;\n      padding-bottom: 60px;\n    }\n    .main {\n      background-color: #121212;\n      margin: 0 auto;\n      width: 100%;\n      max-width: 600px;\n      border-spacing: 0;\n      color: #e5e5e5;\n      border: 1px solid #262626;\n      border-radius: 12px;\n      overflow: hidden;\n      margin-top: 40px;\n    }\n    .header {\n      padding: 32px;\n      text-align: center;\n      border-bottom: 1px solid #262626;\n      background-color: #0a0a0a;\n    }\n    .content {\n      padding: 32px;\n      line-height: 1.6;\n    }\n    .footer {\n      padding: 32px;\n      text-align: center;\n      font-size: 12px;\n      color: #737373;\n    }\n    .button {\n      display: inline-block;\n      padding: 12px 24px;\n      background-color: #2563eb;\n      color: #ffffff;\n      text-decoration: none;\n      border-radius: 6px;\n      font-weight: 500;\n      margin-top: 24px;\n      margin-bottom: 24px;\n    }\n    a {\n      color: #60a5fa;\n      text-decoration: none;\n    }\n    h1 {\n      font-size: 24px;\n      color: #ffffff;\n      margin-top: 0;\n    }\n    h2 {\n      font-size: 20px;\n      color: #ffffff;\n    }\n    p {\n      margin-bottom: 16px;\n    }\n  </style>\n</head>\n<body>\n  <span style=\"display:none !important; visibility:hidden; mso-hide:all; font-size:1px; color:#ffffff; line-height:1px; max-height:0px; max-width:0px; opacity:0; overflow:hidden;\">\n    ${preheader}\n  </span>\n  <center class=\"wrapper\">\n    <table class=\"main\" width=\"100%\">\n      <tr>\n        <td class=\"header\">\n          <div style=\"display:inline-block; width:32px; height:32px; background-color:#2563eb; border-radius:8px; vertical-align:middle; margin-right:12px;\"></div>\n          <span style=\"font-size:20px; font-weight:bold; color:#ffffff; vertical-align:middle;\">LeadLens</span>\n        </td>\n      </tr>\n      <tr>\n        <td class=\"content\">\n          ${content}\n        </td>\n      </tr>\n    </table>\n    <table width=\"100%\" max-width=\"600\" style=\"margin: 0 auto;\">\n      <tr>\n        <td class=\"footer\">\n          <p>\u00A9 ${new Date().getFullYear()} LeadLens Inc. All rights reserved.</p>\n          <p>If you did not request this email, please safely ignore it.</p>\n        </td>\n      </tr>\n    </table>\n  </center>\n</body>\n</html>\n  ".trim();
}
